version: "3.11"

services:
    web:
      build: .
      command: python web/manage.py runserver 0.0.0.0:8000
      container_name: web2
      volumes:
        - .:/web2
      ports:
        - "8000:8000"
    redis:
      image: redis
      expose:
        - 6379
    flower:
      image: mher/flower:0.9.7
      command: ['flower', '--broker=redis://redis:6379', '--port=5555']
      ports:
        - 5557:5555
      depends_on:
        - redis