#version: "3.11"
#
#services:
#  redis:
#    container_name: redis
#    image: redis:alpine
#    restart: unless-stopped
#    ports:
#      - "6380:6379"
#  mailhog:
#    image: mailhog/mailhog
#    container_name: mailhog
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#  web:
#    build: .
#    command: bash -c "python manage.py makemigrations &&
#      python manage.py migrate &&
#      python manage.py runserver 0.0.0.0:8000 "
#    ports:
#      - "8000:8000"
#    environment:
#      - DJANGO_SETTINGS_MODULE=web.settings
#    volumes:
#      - .:/usr/src/web/
#    depends_on:
#      - redis
#      - mailhog
#  celery:
#    build: ./
#    privileged: true
#    command: celery -A web worker --loglevel=info
#    environment:
#      DJANGO_SETTINGS_MODULE: 'web.settings'
#    depends_on:
#      - web
#      - redis
#  dashboard:
#    container_name: dashboard
#    build: ./
#    command:  celery -A web --broker=redis://redis:6379/0 flower
#    ports:
#      - "5555:5555"
#    depends_on:
#      - redis
#      - web
#      - celery
#
#volumes:
#  data:
version: "3.11"

services:
    web:
      build:
        context: /web
      command: python manage.py runserver 0.0.0.0:8000
      container_name: web2
      volumes:
        - .:/web2
      ports:
        - "8000:8000"
      depends_on:
        - "centrifugo"
    centrifugo:
      container_name: centrifugo
      image: centrifugo/centrifugo:v4
      volumes:
        - ./config.json:/centrifugo/config.json
      command:
        centrifugo -c config.json --admin
      ports:
        - "8001:8001"
      ulimits:
        nofile:
          soft: 65535
          hard: 65535
    redis:
      image: redis
      expose:
        - 6379
    flower:
      image: mher/flower:0.9.7
      command: ['flower', '--broker=redis://redis:6379', '--port=5555']
      ports:
        - 5557:5555
      depends_on:
        - redis